name: We do a little building
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
##### JANK ALERT
# we have dependency management at home
      - name: checkout latest NaCL
        uses: actions/checkout@v2
        with:
          repository: 'quat1024/nacl'
          ref: '0.9.3'
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: chmod gradle wrapper
        run: chmod +x ./gradlew
      - name: publish NaCL to maven local
        run: ./gradlew publishToMavenLocal
##### END JANK
      - name: checkout mod
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: chmod gradle wrapper
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
